version: "3"

networks:
  backend:
    driver: bridge

volumes:
  mailcatcher-data:
    driver: local

  var:
    driver: local
  vendor:
    driver: local
  node_modules:
    driver: local

services:
  ec-cube:
    build:
      context: .
    ports:
      - 8080:80
      - 4430:443
    volumes:
      - "var:/var/www/html/var"
      - "vendor:/var/www/html/vendor"
      - "node_modules:/var/www/html/node_modules"
      - ".:/var/www/html:cached"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://dbuser:secret@mysql/webserverdb"
      DATABASE_SERVER_VERSION: 5.7
      DATABASE_CHARSET: 'utf8mb4'

      MAILER_DSN: "smtp://mailcatcher:1025"
    
      USER_ID: ${UID:-}
      GROUP_ID: ${GID:-}

    networks:
      - backend

  ### Mailcatcher ##################################
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - backend
      
  ### Database ##################################      
  mysql:
    image: mariadb:10.3.38-focal
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-database:/var/lib/mysql
      - ./dockerbuild/grant_to_dbuser.sql:/docker-entrypoint-initdb.d/grant_to_dbuser.sql
    ports:
      - 13306:3306
    networks:
      - backend
    healthcheck:
      test: mysqladmin ping
      interval: 3s
      timeout: 3s
      retries: 3

  ### phpmyadmin ##################################      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - backend
  
