#!/bin/sh
set -e

if [ -n "${USER_ID}" ]; then
    usermod -u ${USER_ID} -o www-data
fi
if [ -n "${GROUP_ID}" ]; then
    groupmod -g ${GROUP_ID} www-data
fi

if [ ! -d ${APACHE_DOCUMENT_ROOT}/vendor/bin ]; then
    composer -n require symfony/console "6.1.*"
    composer install \
        --no-scripts \
        --no-autoloader \
        --no-plugins \
        -d ${APACHE_DOCUMENT_ROOT}
    composer dumpautoload -o --apcu
    chown -R www-data: vendor
fi

if [ ! -e ${APACHE_DOCUMENT_ROOT}/.install ]; then
    touch ${APACHE_DOCUMENT_ROOT}/.install
    cp ${APACHE_DOCUMENT_ROOT}/.env.dist ${APACHE_DOCUMENT_ROOT}/.env
   
    composer run-script installer-scripts
    composer run-script auto-scripts
    find ${APACHE_DOCUMENT_ROOT} \( -path ${APACHE_DOCUMENT_ROOT}/vendor -prune \) -or \( -path ${APACHE_DOCUMENT_ROOT}/.git -prune \) -or -print0 \
        | xargs -0 chown www-data:www-data
    find ${APACHE_DOCUMENT_ROOT} \( -path ${APACHE_DOCUMENT_ROOT}/vendor -prune \) -or \( -path ${APACHE_DOCUMENT_ROOT}/.git -prune \) -or \( -type d -print0 \) \
        | xargs -0 chmod g+s
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
